### ISSUE TITLE
安装不了啊

### ISSUE THREAD

**Issue by CharlesYe8848** [yddeng/filecloud#3]
执行第二个命令提示
错误提示：
filecloud.go:4:2: no required module provides package github.com/yddeng/filecloud/server; to add it:
	go get github.com/yddeng/filecloud/server

**Comment by yddeng** [comment]
代码没有下载完整吧

**Comment by CharlesYe8848** [comment]
> 代码没有下载完整吧

我执行第一个命令下载完整了

**Comment by yddeng** [comment]
在filecloud 根目录执行`go run server/main/filecloud.go config.toml` 。

**Comment by CharlesYe8848** [comment]
我下载的根目录是这个～/go/pkg/mod/github.com/yddeng/filecloud@v0.0.0-20210412032704-cf14712d0bcd

**Comment by yddeng** [comment]
哦，你是用mod下载的。 `export GO111MODULE=off` 之后执行 `go get github.com/yddeng/filecloud` 。项目下载到gopath/src

**Comment by CharlesYe8848** [comment]
yezi@yezideMacBook-Pro ~ % go get github.com/yddeng/filecloud
package github.com/yddeng/filecloud: no Go files in /Users/yezi/go/src/github.com/yddeng/filecloud

**Comment by yddeng** [comment]
对了这回，进 `/Users/yezi/go/src/github.com/yddeng/filecloud`这个路径下 执行`go run server/main/filecloud.go config.toml `

**Comment by CharlesYe8848** [comment]
<img width="1427" alt="WX20210413-114750@2x" src="https://user-images.githubusercontent.com/26808857/114494023-307fdc00-9c4e-11eb-9004-1967d91f4d00.png">
提示网络错误上传不了文件。
![image](https://user-images.githubusercontent.com/26808857/114494105-4f7e6e00-9c4e-11eb-8661-f4c86b9efdf0.png)

**Comment by yddeng** [comment]
是不是服务器没有启动或者没有启动成功，这个页面通过app/index.html 直接打开的

**Comment by CharlesYe8848** [comment]
![image](https://user-images.githubusercontent.com/26808857/114494488-109ce800-9c4f-11eb-88ee-3044ba430e60.png)
貌似shi是启动成功了啊

**Comment by yddeng** [comment]
请求list 会有日志记录`handler.go:73: fileList cloud`
```
[DEBUG] 2021/04/13 11:51:42.968392 logger.go:9: filecloud logger init
[INFO]  2021/04/13 11:51:42.969469 config.go:24: &{127.0.0.1:9987 ./app cloud 2 false}
[DEBUG] 2021/04/13 11:51:55.280240 handler.go:73: fileList cloud
[INFO]  2021/04/13 11:52:09.245068 handler.go:197: fileCheck &{cloud v2-d311951f8da9f2e741500cb24070fada_720w.jpg 67aeb0656404026bc87af946e8a3ff81 1 47127}
[INFO]  2021/04/13 11:52:09.304015 handler.go:311: fileUpload 127.0.0.1:59862 cloud v2-d311951f8da9f2e741500cb24070fada_720w.jpg 67aeb0656404026bc87af946e8a3ff81 1
[INFO]  2021/04/13 11:52:09.305418 fileInfos.go:87: input cloud/v2-d311951f8da9f2e741500cb24070fada_720w.jpg from cloud/v2-d311951f8da9f2e741500cb24070fada_720w.jpg.part1 written 47127
[DEBUG] 2021/04/13 11:52:09.309984 handler.go:73: fileList cloud
```

**Comment by CharlesYe8848** [comment]
哦哦，我知道了，我把配置文件127.0.0.1改成我远端服务器的地址，现在就可以了，哈哈哈，感谢作者耐心的解答～

**Comment by yddeng** [comment]
调试器也是显示list请求失败了

**Comment by yddeng** [comment]
OKOK，欢迎提出建议及修改。

**Comment by CharlesYe8848** [comment]
如果后续这个加个登录环节的认证（怕别人任意访问）及分享给别人可以设置是否需要密码访问（可以将某些文件授权分享给别人），就相当nice啦
