### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by CharlesYe8848** [yddeng/filecloud#4]
![image](https://user-images.githubusercontent.com/26808857/114503836-7a71bd80-9c60-11eb-9ba6-e0ea9c44ab67.png)

这是我看到最简洁的网盘了，2个建议不知可否采纳：
1、在cloud文件夹下面创建的文件夹或者文件刷新页面后没有显示在网盘中，重启可以显示出来
2、html文件在上传后可否访问，目前只能下载
3、网盘可否要登录才能访问所有文件，同时也能满足分享某个链接给其它人访问的诉求
4、如果视频能在线观看，那可是太棒了
5、上面那个空间是啥，我貌似还没用那么多啊

**Comment by yddeng** [comment]
1. 通过web前端创建应该是可以直接展示的。如果是在后端文件下创建，会涉及到readme中的问题。
2. 目前只能下载。做到直接展示，要根据文件类型 jpg、txt、docx等用到不同读取方式。目前个人前端能力有限，这个方面实现较困难，希望有大佬来实现。
3. 目前只是做到个人的存储需求，还没有涉及到分享等功能。有机会应该可以做的，干倒百度网盘 :)
4. 同问题2。
5. 这个是读取的计算机物理磁盘容量。 实际能存储多少东西的限制也在这里。

**Comment by yddeng** [comment]
问题1补充：只有服务启动时才会扫描cloud下目录结构，运行中目录结构发生变化对于服务器来说是不知道的。同时运行中修改目录后会导致前端请求报错，比如删除某一目录，然后前端访问这个目录。要做到结构变化的感知就需要监听这里的事件，实时修正目录结构。

**Comment by CharlesYe8848** [comment]
明白了，感谢回复～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yddeng/filecloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yddeng/filecloud] 建议 (#4)





 
问题1补充：只有服务启动时才会扫描cloud下目录结构，运行中目录结构发生变化对于服务器来说是不知道的。同时运行中修改目录后会导致前端请求报错，比如删除某一目录，然后前端访问这个目录。要做到结构变化的感知就需要监听这里的事件，实时修正目录结构。

**Comment by CharlesYe8848** [comment]
您好，你发的邮件我已收到。
